[pi_control]
pi1.local ansible_host=localhost ansible_connection=local

[pi_compute]
pi2.local ansible_host=pi2.local
pi3.local ansible_host=pi3.local
pi4.local ansible_host=pi4.local
pi5.local ansible_host=pi5.local
pi6.local ansible_host=pi6.local
pi7.local ansible_host=pi7.local
pi8.local ansible_host=pi8.local

[pi_cluster:children]
pi_control
pi_compute

[pi_cluster:vars]
ansible_user=pi
ansible_password=icer
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no' 