# This playbook sets up python on all the nodes. Installs a virtual environment and the necessary packages.
# This is the same as ssh-ing into each node and running the commands below.
# sudo apt install python3-pip python3-venv python3-dev
# python3 -m venv /home/pi/venv
# source /home/pi/venv/bin/activate
# pip install pyzmq numpy pygame matplotlib

---
- name: Set up python virtual environment on all nodes
  hosts: pi_cluster
  become: yes
  
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-dev
        state: present
        update_cache: yes
        
    - name: Create virtual environment
      become_user: pi
      command: python3 -m venv /home/pi/venv
      args:
        creates: /home/pi/venv/bin/activate
        
    - name: Install Python dependencies
      become_user: pi
      pip:
        name:
          - pyzmq
          - numpy
          - pygame
          - matplotlib
        virtualenv: /home/pi/venv